In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from selenium import webdriver
import time
from matplotlib import pyplot as plt

In [4]:
urla = input(("Enter url : "))
# "https://www.autoguide.com/used-cars/used-cars.html"

In [5]:
driver=webdriver.Firefox(executable_path="C:/Users/DELL/Downloads/geckodriver.exe")
#set the value of executable path
driver.get(urla)

In [6]:
page_source=driver.page_source

In [7]:
#parsing the page
soup=BeautifulSoup(page_source,'html.parser')

In [8]:
#All the data present in a page is present in id container
data=soup.findAll('div',{"id":"container"})
#printing the extracted data of a single page
for info in data:
    print(info.text)

2021 Nissan Rogue 101



Hyundai Kona: All We Know



Your Engine Oil Encyclopedia



Best Car Vacuums




















Auto News
Spy Photos
Top 10
Auto Shows



New Cars
Car Comparisons
Buyer’s Guides
Future Cars
Auto insurance

Acura
Alfa Romeo
Aston Martin
Audi
Bentley
BMW
Buick
Cadillac
Chevrolet
Chrysler
Dodge
Faraday Future
Ferrari
Fiat
Ford
Genesis
GMC
Honda
Hyundai
Infiniti
Jaguar
Jeep
Kia
Lamborghini
Land Rover
Lexus
Lincoln
Lotus
Lucid Motors
Maserati
Mazda
McLaren
Mercedes-Benz
Mini
Mitsubishi
Nissan
Pagani
Porsche
Ram
Rivian
Rolls-Royce
Smart
Subaru
Tesla
Toyota
Volkswagen
Volvo


Used Cars
Car Reviews
Auto Resources
Car Loan
Auto Insurance
Auto Glass Repair
Auto Warranty



Video











Parts & Accessories
Tires & Wheels
Car Care
Tools & Equipment
Electronics
Deals & Gift Ideas





















googletag.cmd.push(function() { deployads.push(function() {deployads.gpt.display('AutoGuide_com_Position4_AUTO'); }); });












Your Name:



Your Email:



Email Recipient:












Close







		Used Cars for Sale



Email a friend
Print this page




			googletag.cmd.push(function() { deployads.push(function() {deployads.gpt.display('AutoGuide_com_x100_AUTO'); }); });





Our used car classifieds section provides an easy-to-search listing of  vehicles. Find compact cars, subcompact cars, family sedans,
                luxury cars, sportscars, exotics, hybrids, SUVs, trucks and crossovers for sale  in your area. Start searching our database of used cars for sale now.







googletag.cmd.push(function() { deployads.push(function() {deployads.gpt.display('AutoGuide_com_x21_AUTO'); }); });








Select Make




...then Model



























Refine Your Results

Year


2021

	(588930)



2020

	(1025656)



2019

	(168548)



2018

	(163914)



2017

	(219495)



2016

	(107313)



2015

	(96167)



2014

	(84600)



2013

	(80619)



2012

	(66859)



2011

	(57679)



2010

	(44362)



2005 - 2009

	(177785)



2000 - 2004

	(65898)



1995 - 1999

	(14433)



1990 - 1994

	(3928)



1985 - 1989

	(2364)



1980 - 1984

	(1185)



1970 - 1979

	(4805)



1960 - 1969

	(5831)



1950 - 1959

	(1894)



1940 - 1949

	(391)



1930 - 1939

	(318)



1920 - 1929

	(267)



 TO

	(1225)



More »
Less «



Make


Ford

	(444916)



Chevrolet

	(359673)



Toyota

	(281856)



Honda

	(280630)



Nissan

	(201090)



Jeep

	(147229)



Hyundai

	(119850)



Kia

	(108558)



GMC

	(89100)



Ram

	(83037)



Subaru

	(79957)



Dodge

	(79361)



Volkswagen

	(77605)



BMW

	(62903)



Mercedes-Benz

	(61169)



Mazda

	(59007)



Buick

	(53965)



Lexus

	(51347)



Audi

	(46344)



Cadillac

	(42931)



Acura

	(41432)



Chrysler

	(32803)



Lincoln

	(32174)



Infiniti

	(23869)



Volvo

	(23373)



Mitsubishi

	(19435)



Land Rover

	(12829)



Porsche

	(12034)



Mini

	(8329)



Jaguar

	(6196)



Pontiac

	(5900)



Alfa Romeo

	(3637)



Scion

	(3290)



Maserati

	(3178)



Genesis

	(3037)



Mercury

	(3033)



Saturn

	(2865)



FIAT

	(2645)



Tesla

	(1782)



Hummer

	(1333)



Ferrari

	(1271)



Bentley

	(1208)



Suzuki

	(1003)



Oldsmobile

	(953)



Aston Martin

	(740)



Smart

	(663)



Rolls-Royce

	(631)



Saab

	(625)



Plymouth

	(623)



Lamborghini

	(607)



More »
Less «



Model


F-150

	(105476)



Silverado 1500

	(68121)



CR-V

	(66146)



Civic

	(61799)



Camry

	(57832)



Accord

	(56378)



Equinox

	(54358)



1500

	(53217)



Escape

	(52333)



Corolla

	(50202)



Explorer

	(46607)



Fusion

	(40872)



Grand Cherokee

	(38949)



Highlander

	(38720)



Altima

	(38356)



RAV4

	(35763)



Rogue

	(31384)



Wrangler

	(31187)



Sentra

	(30095)



Trax

	(29322)



Pilot

	(27633)



Jetta

	(26595)



Edge

	(26550)



Traverse

	(26490)



Cherokee

	(26196)



Tucson

	(25605)



Malibu

	(25536)



Odyssey

	(24654)



CX-5

	(24205)



Elantra

	(24214)



Sierra 1500

	(23809)



F-250

	(23203)



Outback

	(22988)



Sonata

	(22817)



Tacoma

	(22273)



Mustang

	(21184)



Compass

	(19777)



Acadia

	(17998)



Santa Fe

	(17772)



Tahoe

	(17773)



Sportage

	(17012)



Forte

	(16903)



Terrain

	(17135)



Atlas

	(16546)



RX

	(16326)



MDX

	(15971)



Crosstrek

	(15917)



Charger

	(15715)



Soul

	(15437)



Grand Caravan

	(15387)



More »
Less «



Trim


SE

	(187668)



LT

	(170109)



S

	(117399)



LX

	(102391)



Sport

	(101468)



XLT

	(98463)



EX

	(92368)



LE

	(78531)



SEL

	(72342)



SV

	(67705)



Limited Edition

	(66896)



LS

	(61347)



Touring

	(57962)



Limited

	(57161)



EXL

	(48770)



XLE

	(48733)



Premium

	(47018)



XL

	(44426)



SLT

	(39875)



Base

	(39122)



Latitude

	(27622)



350

	(25474)



SL

	(25081)



Lariat

	(24450)



SXT

	(24328)



SLE

	(22440)



Platinum

	(22059)



Titanium

	(21652)



Denali

	(21591)



SR

	(21314)



GT

	(21066)



Premium Plus

	(20593)



SR5

	(18773)



Preferred

	(18385)



LTZ

	(18586)



Laramie

	(17910)



Premier

	(17893)



Tradesman

	(17463)



Reserve

	(16237)



Technology

	(16206)



Work Truck

	(15757)



Grand Touring

	(15395)



Big Horn/Lone Star

	(14720)



300

	(13719)



Premium Luxury

	(12929)



Laredo

	(12593)



ST

	(12509)



Essence

	(12130)



Select

	(11192)



R/T

	(10839)



More »
Less «



Location


Houston, TX

	(35980)



Jacksonville, FL

	(26200)



San Antonio, TX

	(23550)



Miami, FL

	(19716)



Orlando, FL

	(17441)



Dallas, TX

	(16091)



Tampa, FL

	(15490)



Columbus, OH

	(13397)



Las Vegas, NV

	(11899)



Phoenix, AZ

	(10734)



Austin, TX

	(10607)



Indianapolis, IN

	(10353)



Charlotte, NC

	(10275)



Oklahoma City, OK

	(9308)



Cincinnati, OH

	(9148)



El Paso, TX

	(8908)



Baton Rouge, LA

	(8893)



San Diego, CA

	(8685)



Oakland, CA

	(8574)



San Jose, CA

	(8505)



Louisville, KY

	(8393)



Portland, OR

	(7942)



Sacramento, CA

	(7866)



Colorado Springs, CO

	(7859)



Chicago, IL

	(7858)



Los Angeles, CA

	(7787)



Cadillac, MI

	(7668)



Raleigh, NC

	(7557)



Omaha, NE

	(7504)



Fort Myers, FL

	(7379)



Huntsville, AL

	(7340)



Albuquerque, NM

	(6996)



Denver, CO

	(6969)



West Palm Beach, FL

	(6904)



Richmond, VA

	(6351)



Saint Louis, MO

	(6152)



Arlington, TX

	(6126)



Salt Lake City, UT

	(6110)



Marietta, GA

	(6026)



Tucson, AZ

	(5994)



Mesa, AZ

	(5926)



Fontana, CA

	(5901)



Memphis, TN

	(5809)



Columbia, SC

	(5686)



Tacoma, WA

	(5673)



Fort Worth, TX

	(5672)



Daytona Beach, FL

	(5638)



West Chester, PA

	(5634)



Lubbock, TX

	(5633)



Philadelphia, PA

	(5630)



More »
Less «



Body Style


SUV

	(1337187)



Sedan

	(774320)



Pickup

	(435054)



Hatchback

	(102948)



Minivan

	(86320)



Coupe

	(74522)



Wagon

	(59146)



Van

	(35881)



Convertible

	(29636)



Chassis

	(24345)



Midsize Car

	(2395)



Small Special Purpose Vehicle

	(2080)



Standard Pickup Truck

	(1154)



Compact Car

	(821)



Special Purpose Vehicle

	(634)



Large Car

	(498)



Vehicles Over 8,500 lbs

	(335)



Subcompact Car

	(324)



Passenger Van

	(204)



Cargo Van

	(113)



Small Station Wagon

	(86)



Small Pickup Truck

	(71)



Fourgon Cargo

	(56)



Two Seater

	(52)



Petite Familiale

	(41)





	(24)



Minicompact Car

	(12)



Familiale Intermédiaire

	(8)



Midsize Station Wagon

	(3)



More »
Less «



Price


less than $10,501

	(277369)



$10,501 - $16,500

	(260655)



$16,501 - $21,500

	(300239)



$21,501 - $25,000

	(258254)



$25,001 - $29,000

	(293309)



$29,001 - $34,500

	(292420)



$34,501 - $41,000

	(275707)



$41,001 - $50,000

	(289137)



$50,001+

	(282175)



unknown

	(455201)



More »
Less «



Mileage


less than 5

	(319792)



5 - 6

	(246189)



7 - 10

	(265800)



11 - 100

	(266289)



101 - 22,415

	(274743)



22,416 - 41,977

	(276201)



41,978 - 77,899

	(276969)



77,900 - 121,207

	(275828)



121,208+

	(274611)



unknown

	(508044)



More »
Less «



Exterior Color


White

	(716585)



Black

	(568291)



Gray

	(488862)



Silver

	(382608)



Blue

	(272129)



Red

	(252732)



Green

	(37351)



Beige

	(27728)



Brown

	(23977)



Burgundy

	(16192)



Gold

	(16178)



Orange

	(14646)



Bronze

	(8264)



Yellow

	(7117)



Purple

	(4280)



Turquoise

	(2228)



Pink

	(102)



Undetermined

	(2)



Maroon

	(29)



Teal

	(3)



More »
Less «



Transmission


Automatic

	(2870891)



Manual

	(63569)



unknown

	(315)



Constant Velocity

	(8)






MPG


less than 19

	(412848)



19 - 21

	(489109)



22 - 23

	(381660)



24 - 25

	(294615)



26 - 28

	(407788)



29 - 31

	(340574)



32+

	(380339)



unknown

	(277533)






Fuel


Gasoline

	(2541198)



Flexible-Fuel

	(188861)



Hybrid

	(114509)



Diesel

	(88566)



Electric

	(16554)



Alternative

	(472)






Engine


4 Cyl

	(1597812)



6 Cyl

	(879360)



8 Cyl

	(426095)



3 Cyl

	(31803)



Electric

	(16197)



5 Cyl

	(8364)



10 Cyl

	(2820)



12 Cyl

	(2514)



Rotary

	(188)



16 Cyl

	(12)



Hybrid

	(33)



unknown

	(9)



More »
Less «



Details


Air Conditioning

	(2444775)



Anti-Lock Brakes

	(2313454)



AM/FM

	(2314316)



Adjustable Steering Wheel

	(2308412)



Power Steering

	(2144104)



Power Mirrors

	(2075187)



Steering Wheel Controls

	(2065508)



Front Airbags (Passenger)

	(2064628)



Front Airbags (Driver)

	(1990468)



Stability Control

	(1959318)



Tire Pressure Monitoring System

	(1954475)



Traction Control

	(1938488)



Power Windows

	(1881845)



Rear Window Defroster

	(1871246)



Automatic Headlights

	(1843761)



Vanity Mirror/Light

	(1841094)



Anti-Theft System

	(1794597)



Trip Computer

	(1773449)



Braking Assist

	(1717718)



4-Wheel Disc Brakes

	(1703230)



Cruise Control

	(1707615)



Rear-View Camera

	(1671164)



Alloy Wheels

	(1665506)



Front Side Airbags (Driver)

	(1607134)



Passenger Sensing Airbag

	(1606962)



Heated Mirrors

	(1562133)



Intermittent Wipers

	(1534867)



Power Locks

	(1474985)



Satellite Radio

	(1474961)



Handsfree/Bluetooth Integration

	(1440973)



Tachometer

	(1390158)



Power Seat (Driver)

	(1327108)



Thermometer

	(1321956)



Split/Folding Seats

	(1298456)



Heated Seats

	(1276381)



Reading Lights

	(1282439)



Keyless Entry

	(1233128)



Front Bucket Seats

	(1215870)



Fog Lights

	(1207656)



Remote Keyless Entry

	(1194976)



MP3

	(1199317)



Illuminated Entry

	(1177627)



Auto-Dimming Mirror

	(1136824)



Daytime Running Lights

	(1139611)



Floor Mats

	(1137612)



Door Bin

	(1121442)



Front Center Armrest

	(1084248)



Panic Button

	(1044593)



Body Colored Bumpers

	(1040005)



Cloth Seats

	(1034734)



More »
Less «








Choose sort order
Price Ascending
Price Descending
Distance Ascending
Distance Descending
Mileage Ascending
Mileage Descending

2984466 vehicles found







1
2
3
4
5

>








				25 photos










$599 2014 GMC Terrain SLE-2



 Mileage: 33,995
Location: STEINBACH
MPG: city 23
hwy 34
combined 28


Features THIS PERFECT 5 SEATER IS GREAT ON GAS AND HAS HEATED SEATS, REAR CAMERA, MY LINK. Don't hesitate come in and see the team here at Ledingham GM in Steinbach, arrange a test drive and see for yourself...


Contact Seller



Contact the Seller
LEDINGHAM PONTIAC BUICK LTD.
(204)326-3451






















Enter Your Message Here*





View Details








				17 photos










$2,899 2009 Hyundai Accent L



 Mileage: 79,886
Location: Granby
MPG: city 32
hwy 39
combined 35



Contact Seller



Contact the Seller
GRANBY CHEVROLET CADILLAC BUICK GMC INC.
4503724242






















Enter Your Message Here*





View Details








				10 photos










$3,795 2008 Pontiac Montana SV6 1SA



 Mileage: 155,373
Location: AMOS
MPG: city 18
hwy 29
combined 23


Features veuillez contacter Mathieu: m.audette@garagetardif.com


Contact Seller



Contact the Seller
GARAGE TARDIF LTEE
(819)732-5314






















Enter Your Message Here*





View Details





googletag.cmd.push(function() { deployads.push(function() {deployads.gpt.display('Autoguide_com_300x250_Mobile_Listing3_AUTO'); }); });







				9 photos










$4,195 2007 Ford Focus SES



 Mileage: 129,783
Location: MILTON
MPG: city 26
hwy 37
combined 31


Features YOUR FULL LINE DEALERSHIP.....WE ARE COMMITTED TO 100% CUSTOMER SATISFACTION


Contact Seller



Contact the Seller
WALLACE PONTIAC BUICK CADILLAC LTD.
(905)878-2355






















Enter Your Message Here*





View Details








				13 photos










$4,495 2008 Hyundai Accent L



 Mileage: 67,000
Location: PLESSISVILLE
MPG: city 34
hwy 39
combined 36


Features EN EXCELLENTE CONDITION ET TRES PROPRE, INSPECTION COMPLETE


Contact Seller



Contact the Seller
DUBOIS & FRERES LIMITEE
(819)362-7377






















Enter Your Message Here*





View Details








				30 photos










$4,499 2007 Mazda MAZDA6 GS



 Mileage: 159,703
Location: Shawinigan
MPG: city 24
hwy N/A
combined 24


Features Moteur + transmission garantie a vie ACHETEZ D'UN CONCESSIONNAIRE DIGNE DE CONFIANCE,NOUS DONNONS PLUS POUR VOTRE ECHANGE. PASSEZ NOUS VOIR POUR UN ESSAI ROUTIER Vous êtes de Drummondville, Québec,...


Contact Seller



Contact the Seller
Lessard Buick Chev GMC
819-539-8333






















Enter Your Message Here*





View Details








				30 photos










$4,499 2007 Chevrolet Aveo LT



 Mileage: 83,915
Location: Shawinigan
MPG: city 29
hwy 47
combined 37


Features Moteur + transmission garantie a vie EXCELLENTE CONDITION INSPECTÉ ET GARANTIE Financement facile et rapide, au meilleur taux. 2e et 3e chance au crédit aussi disponible sur place. Possibilité de...


Contact Seller



Contact the Seller
Lessard Buick Chev GMC
819-539-8333






















Enter Your Message Here*





View Details








				30 photos










$4,699 2010 Chevrolet Aveo5 LT



 Mileage: 80,100
Location: SAINTE-JULIE
MPG: city 34
hwy 47
combined 40



Contact Seller



Contact the Seller
DES CHAMPS PONTIAC BUICK GMC LTEE
(450)649-9333






















Enter Your Message Here*





View Details








				14 photos










$4,895 2008 Chevrolet Aveo LT



 Mileage: 95,759
Location: NICOLET
MPG: city 29
hwy 47
combined 37



Contact Seller



Contact the Seller
H. AUGER AUTOMOBILES INC.
(819)293-2121






















Enter Your Message Here*





View Details








				30 photos










$4,899 2007 Mazda MAZDA5 GS



 Mileage: 126,624
Location: Shawinigan
MPG: city 24
hwy 29
combined 26


Features Moteur garantie a vie ACHETEZ D'UN CONCESSIONNAIRE DIGNE DE CONFIANCE,NOUS DONNONS PLUS POUR VOTRE ECHANGE. PASSEZ NOUS VOIR POUR UN ESSAI ROUTIER Vous êtes de Drummondville, Québec, Montréal,...


Contact Seller



Contact the Seller
Lessard Buick Chev GMC
819-539-8333






















Enter Your Message Here*





View Details





googletag.cmd.push(function() { deployads.push(function() {deployads.gpt.display('Autoguide_com_300x250_Mobile_Listing10_AUTO'); }); });







				23 photos










$4,950 2009 Pontiac G5 DE BASE



 Mileage: 101,402
Location: VAL D'OR
MPG: city 29
hwy 47
combined 37


Features AUTOMATIQUE - AIR CLIMATISÉ


Contact Seller



Contact the Seller
GAREAU AUTO INC.
(819)825-6880






















Enter Your Message Here*





View Details








				30 photos










$4,992 2009 Chevrolet Aveo LS



 Mileage: 63,200
Location: VILLE LASALLE
MPG: city 34
hwy 47
combined 40


Features Tous nos véhicules sont inspectés. Financement et garantie prolongée disponible sur place. Pour plus d'informations sur ce véhicule, veuillez nous contacter chez GM De LaSalle, 514-595-5666 ou...


Contact Seller



Contact the Seller
CHEVROLET BUICK GMC DE LASALLE
(514)595-5666






















Enter Your Message Here*





View Details








				18 photos










$4,993 2010 Chevrolet Aveo5 LS



 Mileage: 78,657
Location: SAINT-JEAN-SUR-RICHELIEU
MPG: city 34
hwy 47
combined 40


Features *** POUR INFORMATIONS PAR MESSAGE TEXTE CONTACTER PATRICK AU 514-713-9000 *** Ce véhicule comprend une garantie limitée Total Plus de 3 mois ou 5 000 KM de véhicules d'occasion Optimum à compter...


Contact Seller



Contact the Seller
RACINE CHEVROLET LTEE
(450)359-5900






















Enter Your Message Here*





View Details








				15 photos










$4,995 2008 Chevrolet Cobalt LT



 Mileage: 104,415
Location: LA SARRE
MPG: city 26
hwy 47
combined 35


Features Idéal pour étudiant, look sport, économique. à voir Livraison gratuite!


Contact Seller



Contact the Seller
NICOL AUTO INC.
(819)333-5456






















Enter Your Message Here*





View Details








				20 photos










$4,995 2007 Pontiac Wave SE



 Mileage: 85,025
Location: NEW RICHMOND
MPG: city 29
hwy 47
combined 37


Features TRES BAS KILOMETRAGE LIVRAISON PARTOUT AU QUÉBEC ET NEW BRUNSWICK Faites votre offre


Contact Seller



Contact the Seller
A.P. CHEV OLDS PONTIAC BUICK GMC
(418)392-5252






















Enter Your Message Here*





View Details








				0 photos










$4,999 2009 Pontiac G3 Wave SE



 Mileage: 104,900
Location: VILLE LASALLE
MPG: city 34
hwy 47
combined 40


Features Meilleur choix de véhicule usagé en ville au meilleur prix. Financement facile sur place. Toute offre raisonnable accepté. Nous avons en inventaire toute marque de véhicule d occassion tel que...


Contact Seller



Contact the Seller
CHEVROLET BUICK GMC DE LASALLE
(514)595-5666






















Enter Your Message Here*





View Details








				9 photos










$4,999 2008 Kia Rio5 EX



 Mileage: 59,890
Location: VILLE LASALLE
MPG: city 29
hwy 47
combined 37



Contact Seller



Contact the Seller
CHEVROLET BUICK GMC DE LASALLE
(514)595-5666






















Enter Your Message Here*





View Details








				16 photos










$5,133 2009 Chevrolet Cobalt LS



 Mileage: 88,147
Location: SAINT-JEAN-SUR-RICHELIEU
MPG: city 29
hwy 47
combined 37


Features JAMAIS ACCIDENTÉ-- CHAUFFE-BLOC-- RETROVIS. EXT. REGLAGE MANUEL--CHAUFFAGE A COMMANDE ELECTRON.--RADIO: AM/FM STEREO, LECT. DC*** POUR INFORMATIONS PAR MESSAGE TEXTE CONTACTER PATRICK AU 514-713-9000...


Contact Seller



Contact the Seller
RACINE CHEVROLET LTEE
(450)359-5900






















Enter Your Message Here*





View Details








				30 photos










$5,496 2008 Chevrolet Cobalt LS



 Mileage: 89,996
Location: Shawinigan
MPG: city 26
hwy 47
combined 35


Features Moteur + transmission garantie a vie EXCELLENTE CONDITION INSPECTÉ ET GARANTIE Financement facile et rapide, au meilleur taux. 2e et 3e chance au crédit aussi disponible sur place. Possibilité de...


Contact Seller



Contact the Seller
Lessard Buick Chev GMC
819-539-8333






















Enter Your Message Here*





View Details








				30 photos










$5,500 2007 Hyundai Elantra GL



 Mileage: 101,140
Location: Shawinigan
MPG: city 29
hwy 39
combined 34


Features Moteur + transmission garantie a vie ACHETEZ D'UN CONCESSIONNAIRE DIGNE DE CONFIANCE,NOUS DONNONS PLUS POUR VOTRE ECHANGE. PASSEZ NOUS VOIR POUR UN ESSAI ROUTIER Vous êtes de Drummondville, Québec,...


Contact Seller



Contact the Seller
Lessard Buick Chev GMC
819-539-8333






















Enter Your Message Here*





View Details








				1 photo





$19,995 2018 VOLKSWAGEN TIGUAN SE


 Mileage: 48,214
Location: Daytona Beach
MPG: city 22
hwy 27
combined 24



Contact Seller



Contact the Seller
Gunther Volkswagen Daytona Beach

























Enter Your Message Here*





View Details








				31 photos





$19,495 2018 JEEP COMPASS LIMITED EDITION


 Mileage: 13,854
Location: Daytona Beach
MPG: city 22
hwy 31
combined 25



Contact Seller



Contact the Seller
Gunther Volkswagen Daytona Beach

























Enter Your Message Here*






In [9]:
#Finding the titles of cars using find_all
#All the titles are present in a class : title
car_titles = []
a=soup.findAll('a',{"class":"title"})
for i in a :
    print(i.text)#printing titles
    car_titles.append(i.text)#appending values
print(car_titles)#printing titles
len(car_titles)#printing length of list

2014 GMC Terrain SLE-2
2009 Hyundai Accent L
2008 Pontiac Montana SV6 1SA
2007 Ford Focus SES
2008 Hyundai Accent L
2007 Mazda MAZDA6 GS
2007 Chevrolet Aveo LT
2010 Chevrolet Aveo5 LT
2008 Chevrolet Aveo LT
2007 Mazda MAZDA5 GS
2009 Pontiac G5 DE BASE
2009 Chevrolet Aveo LS
2010 Chevrolet Aveo5 LS
2008 Chevrolet Cobalt LT
2007 Pontiac Wave SE
2009 Pontiac G3 Wave SE
2008 Kia Rio5 EX
2009 Chevrolet Cobalt LS
2008 Chevrolet Cobalt LS
2007 Hyundai Elantra GL
2018 VOLKSWAGEN TIGUAN SE
2018 JEEP COMPASS LIMITED EDITION
2021 VOLKSWAGEN ATLAS SEL
2021 VOLKSWAGEN ATLAS SE W/TECHNOLOGY
2018 VOLKSWAGEN PASSAT SEL PREMIUM
2020 VOLKSWAGEN PASSAT SE
2020 VOLKSWAGEN ATLAS CROSS SPORT SE W/TECHNOLOGY
2017 BUICK ENCORE SPORT TOURING
2018 VOLVO XC60 T6 INSCRIPTION
2017 VOLKSWAGEN PASSAT R-LINE
2020 VOLKSWAGEN JETTA R-LINE
2020 CHEVROLET EQUINOX LS 1LS
2019 JEEP CHEROKEE LIMITED EDITION
2020 NISSAN VERSA S
2020 VOLVO S90 T6 R-DESIGN
2020 CHEVROLET EQUINOX LT LT1
2019 HONDA PASSPORT TOURING
2010 FORD EXPEDITION EL XLT SSV
2019 MAZDA CX-5 GRAND TOURING
2020 VOLKSWAGEN ATLAS CROSS SPORT SEL
['2014 GMC Terrain SLE-2', '2009 Hyundai Accent L', '2008 Pontiac Montana SV6 1SA', '2007 Ford Focus SES', '2008 Hyundai Accent L', '2007 Mazda MAZDA6 GS', '2007 Chevrolet Aveo LT', '2010 Chevrolet Aveo5 LT', '2008 Chevrolet Aveo LT', '2007 Mazda MAZDA5 GS', '2009 Pontiac G5 DE BASE', '2009 Chevrolet Aveo LS', '2010 Chevrolet Aveo5 LS', '2008 Chevrolet Cobalt LT', '2007 Pontiac Wave SE', '2009 Pontiac G3 Wave SE', '2008 Kia Rio5 EX', '2009 Chevrolet Cobalt LS', '2008 Chevrolet Cobalt LS', '2007 Hyundai Elantra GL', '2018 VOLKSWAGEN TIGUAN SE', '2018 JEEP COMPASS LIMITED EDITION', '2021 VOLKSWAGEN ATLAS SEL', '2021 VOLKSWAGEN ATLAS SE W/TECHNOLOGY', '2018 VOLKSWAGEN PASSAT SEL PREMIUM', '2020 VOLKSWAGEN PASSAT SE', '2020 VOLKSWAGEN ATLAS CROSS SPORT SE W/TECHNOLOGY', '2017 BUICK ENCORE SPORT TOURING', '2018 VOLVO XC60 T6 INSCRIPTION', '2017 VOLKSWAGEN PASSAT R-LINE', '2020 VOLKSWAGEN JETTA R-LINE', '2020 CHEVROLET EQUINOX LS 1LS', '2019 JEEP CHEROKEE LIMITED EDITION', '2020 NISSAN VERSA S', '2020 VOLVO S90 T6 R-DESIGN', '2020 CHEVROLET EQUINOX LT LT1', '2019 HONDA PASSPORT TOURING', '2010 FORD EXPEDITION EL XLT SSV', '2019 MAZDA CX-5 GRAND TOURING', '2020 VOLKSWAGEN ATLAS CROSS SPORT SEL']

40

In [18]:
mileage = []
location = []
mpg = []
hwy = []
combined = []
#taking empty lists

#All the specifications are inside ul class: stats
spec= soup.find_all("ul",{"class": "stats"})

for i in spec:
    newsoup = BeautifulSoup(str(i),'html.parser')#using parser for scrapping inside details
    lis = newsoup.find_all('li')#finding all li inside ul
    for li in lis:
        
        if 'Mileage' in li.text: # if present 
            mileage.append(li.text.replace(" Mileage:","")) # then append
        if 'Location' in li.text:# if present
            location.append(li.text.replace("Location: ",""))# then append
        if 'MPG' in li.text:# if present
            mpg.append(li.text.replace("MPG: ",""))# then append
        if 'hwy' in li.text:# if present
            hwy.append(li.text.replace("hwy ",""))# then append# then append
        if 'combined' in li.text:# if present
            combined.append(li.text.replace("combined",""))#then append
          
        
#priniting individual lists
print(mileage)
print(location)
print(mpg)
print(hwy)
print(combined)

[' 33,995', ' 79,886', ' 155,373', ' 129,783', ' 67,000', ' 159,703', ' 83,915', ' 80,100', ' 95,759', ' 126,624', ' 101,402', ' 63,200', ' 78,657', ' 104,415', ' 85,025', ' 104,900', ' 59,890', ' 88,147', ' 89,996', ' 101,140', ' 48,214', ' 13,854', ' 7', ' 7', ' 24,470', ' 8', ' 19', ' 28,530', ' 37,542', ' 35,366', ' 10', ' 15', ' 36,665', ' 15,712', ' 60', ' 0', ' 12,052', ' 159,039', ' 21,167', ' 250']
['STEINBACH', 'Granby', 'AMOS', 'MILTON', 'PLESSISVILLE', 'Shawinigan', 'Shawinigan', 'SAINTE-JULIE', 'NICOLET', 'Shawinigan', "VAL D'OR", 'VILLE LASALLE', 'SAINT-JEAN-SUR-RICHELIEU', 'LA SARRE', 'NEW RICHMOND', 'VILLE LASALLE', 'VILLE LASALLE', 'SAINT-JEAN-SUR-RICHELIEU', 'Shawinigan', 'Shawinigan', 'Daytona Beach', 'Daytona Beach', 'Daytona Beach', 'Daytona Beach', 'Daytona Beach', 'Daytona Beach', 'Daytona Beach', 'Gardendale', 'Daytona Beach', 'Daytona Beach', 'Daytona Beach', 'Gardendale', 'Gardendale', 'Roebuck', 'Daytona Beach', 'Gardendale', 'Daytona Beach', 'Daytona Beach', 'Daytona Beach', 'Daytona Beach']
['city 23 ', 'city 32 ', 'city 18 ', 'city 26 ', 'city 34 ', 'city 24 ', 'city 29 ', 'city 34 ', 'city 29 ', 'city 24 ', 'city 29 ', 'city 34 ', 'city 34 ', 'city 26 ', 'city 29 ', 'city 34 ', 'city 29 ', 'city 29 ', 'city 26 ', 'city 29 ', 'city 22 ', 'city 22 ', 'city 17 ', 'city 17 ', 'city 25 ', 'city 23 ', 'city 16 ', 'city 25 ', 'city 22 ', 'city 23 ', 'city 30 ', 'city 26 ', 'city 22 ', 'city 32 ', 'city 21 ', 'city 26 ', 'city 20 ', 'city N/A ', 'city 23 ', 'city 16 ']
['34', '39', '29', '37', '39', 'N/A', '47', '47', '47', '29', '47', '47', '47', '47', '47', '47', '47', '47', '47', '39', '27', '31', '23', '23', '36', '34', '22', '33', '28', '34', '40', '31', '31', '40', '31', '31', '25', 'N/A', '28', '22']
[' 28', ' 35', ' 23', ' 31', ' 36', ' 24', ' 37', ' 40', ' 37', ' 26', ' 37', ' 40', ' 40', ' 35', ' 37', ' 40', ' 37', ' 37', ' 35', ' 34', ' 24', ' 25', ' 19', ' 19', ' 29', ' 27', ' 19', ' 28', ' 24', ' 27', ' 34', ' 28', ' 25', ' 35', ' 25', ' 28', ' 22', ' N/A', ' 25', ' 19']

In [22]:
#Finding the  price on cars using find_all
#All the  price  are present in strong class : price
car_price = []
c = soup.findAll('strong',{"class":"price"})
for i in c :
    print(i.text)
    car_price.append(i.text)#appending in a list
print(car_price)#printing list
len(car_price)#length of list

$599
$2,899
$3,795
$4,195
$4,495
$4,499
$4,499
$4,699
$4,895
$4,899
$4,950
$4,992
$4,993
$4,995
$4,995
$4,999
$4,999
$5,133
$5,496
$5,500
$19,995
$19,495
$39,710
$36,517
$19,995
$21,779
$44,175
$18,999
$36,895
$13,495
$21,100
$22,600
$22,399
$14,680
$52,971
$25,386
$32,995
$8,995
$22,995
$40,674
['$599', '$2,899', '$3,795', '$4,195', '$4,495', '$4,499', '$4,499', '$4,699', '$4,895', '$4,899', '$4,950', '$4,992', '$4,993', '$4,995', '$4,995', '$4,999', '$4,999', '$5,133', '$5,496', '$5,500', '$19,995', '$19,495', '$39,710', '$36,517', '$19,995', '$21,779', '$44,175', '$18,999', '$36,895', '$13,495', '$21,100', '$22,600', '$22,399', '$14,680', '$52,971', '$25,386', '$32,995', '$8,995', '$22,995', '$40,674']

40

In [23]:
#creating dict of scrapped data
dict = {
    'Title' : car_titles ,
    'Mileage' : mileage, 
    'Location': location ,
    'MPG' : mpg ,
    'hwy' : hwy,
    'combined' :combined,
    'Price' : car_price
}

In [24]:
#creating dataframe from dict
df = pd.DataFrame.from_dict(dict,orient = 'index').T
df

,Title,Mileage,Location,MPG,hwy,combined,Price
0,2014 GMC Terrain SLE-2,"33,995",STEINBACH,city 23,34,28,$599
1,2009 Hyundai Accent L,"79,886",Granby,city 32,39,35,"$2,899"
2,2008 Pontiac Montana SV6 1SA,"155,373",AMOS,city 18,29,23,"$3,795"
3,2007 Ford Focus SES,"129,783",MILTON,city 26,37,31,"$4,195"
4,2008 Hyundai Accent L,"67,000",PLESSISVILLE,city 34,39,36,"$4,495"
5,2007 Mazda MAZDA6 GS,"159,703",Shawinigan,city 24,N/A,24,"$4,499"
6,2007 Chevrolet Aveo LT,"83,915",Shawinigan,city 29,47,37,"$4,499"
7,2010 Chevrolet Aveo5 LT,"80,100",SAINTE-JULIE,city 34,47,40,"$4,699"
8,2008 Chevrolet Aveo LT,"95,759",NICOLET,city 29,47,37,"$4,895"
9,2007 Mazda MAZDA5 GS,"126,624",Shawinigan,city 24,29,26,"$4,899"
10,2009 Pontiac G5 DE BASE,"101,402",VAL D'OR,city 29,47,37,"$4,950"
11,2009 Chevrolet Aveo LS,"63,200",VILLE LASALLE,city 34,47,40,"$4,992"
12,2010 Chevrolet Aveo5 LS,"78,657",SAINT-JEAN-SUR-RICHELIEU,city 34,47,40,"$4,993"
13,2008 Chevrolet Cobalt LT,"104,415",LA SARRE,city 26,47,35,"$4,995"
14,2007 Pontiac Wave SE,"85,025",NEW RICHMOND,city 29,47,37,"$4,995"
15,2009 Pontiac G3 Wave SE,"104,900",VILLE LASALLE,city 34,47,40,"$4,999"
16,2008 Kia Rio5 EX,"59,890",VILLE LASALLE,city 29,47,37,"$4,999"
17,2009 Chevrolet Cobalt LS,"88,147",SAINT-JEAN-SUR-RICHELIEU,city 29,47,37,"$5,133"
18,2008 Chevrolet Cobalt LS,"89,996",Shawinigan,city 26,47,35,"$5,496"
19,2007 Hyundai Elantra GL,"101,140",Shawinigan,city 29,39,34,"$5,500"
20,2018 VOLKSWAGEN TIGUAN SE,"48,214",Daytona Beach,city 22,27,24,"$19,995"
21,2018 JEEP COMPASS LIMITED EDITION,"13,854",Daytona Beach,city 22,31,25,"$19,495"
22,2021 VOLKSWAGEN ATLAS SEL,7,Daytona Beach,city 17,23,19,"$39,710"
23,2021 VOLKSWAGEN ATLAS SE W/TECHNOLOGY,7,Daytona Beach,city 17,23,19,"$36,517"
24,2018 VOLKSWAGEN PASSAT SEL PREMIUM,"24,470",Daytona Beach,city 25,36,29,"$19,995"
25,2020 VOLKSWAGEN PASSAT SE,8,Daytona Beach,city 23,34,27,"$21,779"
26,2020 VOLKSWAGEN ATLAS CROSS SPORT SE W/TECHNOLOGY,19,Daytona Beach,city 16,22,19,"$44,175"
27,2017 BUICK ENCORE SPORT TOURING,"28,530",Gardendale,city 25,33,28,"$18,999"
28,2018 VOLVO XC60 T6 INSCRIPTION,"37,542",Daytona Beach,city 22,28,24,"$36,895"
29,2017 VOLKSWAGEN PASSAT R-LINE,"35,366",Daytona Beach,city 23,34,27,"$13,495"
30,2020 VOLKSWAGEN JETTA R-LINE,10,Daytona Beach,city 30,40,34,"$21,100"
31,2020 CHEVROLET EQUINOX LS 1LS,15,Gardendale,city 26,31,28,"$22,600"
32,2019 JEEP CHEROKEE LIMITED EDITION,"36,665",Gardendale,city 22,31,25,"$22,399"
33,2020 NISSAN VERSA S,"15,712",Roebuck,city 32,40,35,"$14,680"
34,2020 VOLVO S90 T6 R-DESIGN,60,Daytona Beach,city 21,31,25,"$52,971"
35,2020 CHEVROLET EQUINOX LT LT1,0,Gardendale,city 26,31,28,"$25,386"
36,2019 HONDA PASSPORT TOURING,"12,052",Daytona Beach,city 20,25,22,"$32,995"
37,2010 FORD EXPEDITION EL XLT SSV,"159,039",Daytona Beach,city N/A,N/A,N/A,"$8,995"
38,2019 MAZDA CX-5 GRAND TOURING,"21,167",Daytona Beach,city 23,28,25,"$22,995"
39,2020 VOLKSWAGEN ATLAS CROSS SPORT SEL,250,Daytona Beach,city 16,22,19,"$40,674"

In [25]:
#Dataframe to csv
df.to_csv('autoguide.csv')