In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from selenium import webdriver
import time
from matplotlib import pyplot as plt

In [2]:
urla = "https://www.wilfselieford.ca/used-vehicles-just-west-of-winnipeg"

In [3]:
driver=webdriver.Firefox(executable_path="C:/Users/DELL/Downloads/geckodriver.exe")
#set the value of executable path
driver.get(urla)

In [4]:
page_source=driver.page_source

In [5]:
#parsing the page
soup=BeautifulSoup(page_source,'html.parser')

In [6]:
#All the data present in a page is present in class vehicle-list center-block max-1200
data=soup.findAll('div',{"class":"vehicle-list center-block max-1200"})
#printing the extracted data of a single page
for info in data:
    print(info.text)

2009 Volkswagen Tiguan HighlinePre-Owned  | 184,530 kmblack leather, power driver's seat, heated front seats, power moonroof, bluetooth     $9,700 ** Price$9,700Stock: CON286     VIN: WVGBV75N89W5412282017 Ford Fusion SEPre-Owned  | 90,588 km2.5L, front wheel drive, bluetooth, back up camera, 5 passenger black cloth, power front seats, remote start     $12,999 ** Price$12,999Stock: 0Y192A     VIN: 3FA6P0H75HR2252332014 Hyundai Tucson GLS FWD 4dr AutoPre-Owned  | 121,643 km5 passenger black leather, remote start, heated seats, sunroof, bluetooth     $14,295 ** Price$14,295Stock: 0Y007B     VIN: KM8JU3AG0EU9010462012 Ford F-150 STX 4WD SuperCab 145"Pre-Owned  | 148,580 km3.7L V6 4X4, 6 passenger, cruise control, fog lights, air conditioning, vinyl floor. 6.5' Box     $16,800 ** Price$16,800Stock: 9X231A     VIN: 1FTEX1EM4CKD005382011 Ford Explorer LimitedPre-Owned  | 160,390 km3.5L 4WD, black leather 6 passnger, adaptive cruise, navigation, heated cooled seats, sunroof, remote start     $17,999 ** Price$17,999Stock: 7X016A     VIN: 1FMHK8F89BGA077712014 Ford Explorer Limited One Owner!Pre-Owned  | 151,340 km Fuel: Gas, Four Wheel Drive --  FEATURES: heated seats, leather seats, navigation, sun/moonroof, cruise control, power seats, rain sensing wipers     $23,295 ** Price$23,295Stock: 0Y024B     VIN: 1FM5K8F87EGC158482020 Ford Escape SEL AWDPre-Owned |   Only 10,715 km!** Low Mileage - One Owner ** 1.5L ecoboost, 5 passenger black interior, remote start, back up camera, heated seats, heated steering wheel, Fordpass connect, power driver's seat.     $28,600 ** Price$28,600Stock: 0Y075A     VIN: 1FMCU9H64LUA024852015 GMC Yukon XL Denali - New Tires - DVDPre-Owned  | 149,562 km7 passenger, black leather interior, navigation, power heated cooled front seats, 2nd row heated bucket seats     $42,900 ** Price$42,900Stock: 9X317A     VIN: 1GKS2JKJ1FR6319142020 Ford Explorer XLT 4WDPre-Owned |   Only 10,941 km!10941 kms! 2.3L ecoboot, 7 passenger black leather, heated steering wheel, power heated front seats. 2nd row heated seats, remote start, Fordpass connect, power liftgate.     $44,300 ** Price$44,300Stock: 0Y375A     VIN: 1FMSK8DH6LGB77838Not finding what you want?Tell us what you are looking fororReset filters and search again* Disclaimer: For a more in depth breakdown, click on the vehicle to view the detail page. While we make every attempt to list prices on our website as accurately as possible, in all cases buyers must see the dealer for official pricing details and credit qualifications for a price to be binding. Payments and financing available OAC. * In such case that manufacturer incentives are listed, these represent possible cash incentives available for certain vehicles of this year/make/model. Not all incentives are available in all areas, on all trims/configurations, or to all buyers. As always, consult the dealer for official details and qualifications.

In [7]:
#Finding the titles of cars using find_all
#All the titles are present in h4 class : vehicle-header media-heading
car_titles = []
a=soup.findAll('h4',{"class":"vehicle-header media-heading"})
for i in a :
    print(i.text)#printing titles
    car_titles.append(i.text)#appending values
print(car_titles)#printing titles
len(car_titles)#printing length of list

2009 Volkswagen Tiguan Highline
2017 Ford Fusion SE
2014 Hyundai Tucson GLS FWD 4dr Auto
2012 Ford F-150 STX 4WD SuperCab 145"
2011 Ford Explorer Limited
2014 Ford Explorer Limited One Owner!
2020 Ford Escape SEL AWD
2015 GMC Yukon XL Denali - New Tires - DVD
2020 Ford Explorer XLT 4WD
['2009 Volkswagen Tiguan Highline', '2017 Ford Fusion SE', '2014 Hyundai Tucson GLS FWD 4dr Auto', '2012 Ford F-150 STX 4WD SuperCab 145"', '2011 Ford Explorer Limited', '2014 Ford Explorer Limited One Owner!', '2020 Ford Escape SEL AWD', '2015 GMC Yukon XL Denali - New Tires - DVD', '2020 Ford Explorer XLT 4WD']

9

In [8]:
#Finding the description of cars using find_all
#All the description are present in div class : vehicle-highlights-tagline
car_description = []
b = soup.findAll('div',{"class":"vehicle-highlights-tagline"})
for i in b :
    print(i.text)
    car_description.append(i.text)#apppending inside a separate list
print(car_description)#printing list
len(car_description)#length of list

black leather, power driver's seat, heated front seats, power moonroof, bluetooth
2.5L, front wheel drive, bluetooth, back up camera, 5 passenger black cloth, power front seats, remote start
5 passenger black leather, remote start, heated seats, sunroof, bluetooth
3.7L V6 4X4, 6 passenger, cruise control, fog lights, air conditioning, vinyl floor. 6.5' Box
3.5L 4WD, black leather 6 passnger, adaptive cruise, navigation, heated cooled seats, sunroof, remote start
** Low Mileage - One Owner ** 1.5L ecoboost, 5 passenger black interior, remote start, back up camera, heated seats, heated steering wheel, Fordpass connect, power driver's seat.
7 passenger, black leather interior, navigation, power heated cooled front seats, 2nd row heated bucket seats
10941 kms! 2.3L ecoboot, 7 passenger black leather, heated steering wheel, power heated front seats. 2nd row heated seats, remote start, Fordpass connect, power liftgate.
["black leather, power driver's seat, heated front seats, power moonroof, bluetooth", '2.5L, front wheel drive, bluetooth, back up camera, 5 passenger black cloth, power front seats, remote start', '5 passenger black leather, remote start, heated seats, sunroof, bluetooth', "3.7L V6 4X4, 6 passenger, cruise control, fog lights, air conditioning, vinyl floor. 6.5' Box", '3.5L 4WD, black leather 6 passnger, adaptive cruise, navigation, heated cooled seats, sunroof, remote start', "** Low Mileage - One Owner ** 1.5L ecoboost, 5 passenger black interior, remote start, back up camera, heated seats, heated steering wheel, Fordpass connect, power driver's seat.", '7 passenger, black leather interior, navigation, power heated cooled front seats, 2nd row heated bucket seats', '10941 kms! 2.3L ecoboot, 7 passenger black leather, heated steering wheel, power heated front seats. 2nd row heated seats, remote start, Fordpass connect, power liftgate.']

8

In [9]:
#Finding the sales price on cars using find_all
#All the  sales price  are present in div class : vehicle-price-full
car_price = []
c = soup.findAll('div',{"class":"vehicle-price-full"})
for i in c :
    print(i.text)
    car_price.append(i.text.replace("* Price",""))#appending in a list
print(car_price)#printing list
len(car_price)#length of list

* Price$9,700
* Price$12,999
* Price$14,295
* Price$16,800
* Price$17,999
* Price$23,295
* Price$28,600
* Price$42,900
* Price$44,300
['$9,700', '$12,999', '$14,295', '$16,800', '$17,999', '$23,295', '$28,600', '$42,900', '$44,300']

9

In [10]:

certification = []#taking empty list

c = soup.findAll('div',{"class":"vehicle-specs"})#scrapping cerification
for i in c :
    a = i.find('span').text.split('|')[0]#finding using split
    certification.append(a)#appending in lisy
    
print(certification)#printing list

['Pre-Owned  ', 'Pre-Owned  ', 'Pre-Owned  ', 'Pre-Owned  ', 'Pre-Owned  ', 'Pre-Owned  ', 'Pre-Owned ', 'Pre-Owned  ', 'Pre-Owned ']

In [11]:
#creating dict of scrapped data
dict = {
    'Title' : car_titles ,
    'Description' : car_description , 
    'Certification ': certification ,
    'Price' : car_price
}

In [12]:
df = pd.DataFrame.from_dict(dict,orient = 'index').T
df

,Title,Description,Certification,Price
0,2009 Volkswagen Tiguan Highline,"black leather, power driver's seat, heated fro...",Pre-Owned,"$9,700"
1,2017 Ford Fusion SE,"2.5L, front wheel drive, bluetooth, back up ca...",Pre-Owned,"$12,999"
2,2014 Hyundai Tucson GLS FWD 4dr Auto,"5 passenger black leather, remote start, heate...",Pre-Owned,"$14,295"
3,"2012 Ford F-150 STX 4WD SuperCab 145""","3.7L V6 4X4, 6 passenger, cruise control, fog ...",Pre-Owned,"$16,800"
4,2011 Ford Explorer Limited,"3.5L 4WD, black leather 6 passnger, adaptive c...",Pre-Owned,"$17,999"
5,2014 Ford Explorer Limited One Owner!,"** Low Mileage - One Owner ** 1.5L ecoboost, 5...",Pre-Owned,"$23,295"
6,2020 Ford Escape SEL AWD,"7 passenger, black leather interior, navigatio...",Pre-Owned,"$28,600"
7,2015 GMC Yukon XL Denali - New Tires - DVD,"10941 kms! 2.3L ecoboot, 7 passenger black lea...",Pre-Owned,"$42,900"
8,2020 Ford Explorer XLT 4WD,None,Pre-Owned,"$44,300"

In [13]:
df['Dealer'] = 'wilfselieford'
df['Condition'] = 'Used'

In [14]:
split_title = df["Title"].str.split(" ", n = 2, expand = True) 
# splitting Tile column 
df["Make Year"]= split_title[0] 
df["Make"]= split_title[1] 
df["Model"]= split_title[2] 
df

,Title,Description,Certification,Price,Dealer,Condition,Make Year,Make,Model
0,2009 Volkswagen Tiguan Highline,"black leather, power driver's seat, heated fro...",Pre-Owned,"$9,700",wilfselieford,Used,2009,Volkswagen,Tiguan Highline
1,2017 Ford Fusion SE,"2.5L, front wheel drive, bluetooth, back up ca...",Pre-Owned,"$12,999",wilfselieford,Used,2017,Ford,Fusion SE
2,2014 Hyundai Tucson GLS FWD 4dr Auto,"5 passenger black leather, remote start, heate...",Pre-Owned,"$14,295",wilfselieford,Used,2014,Hyundai,Tucson GLS FWD 4dr Auto
3,"2012 Ford F-150 STX 4WD SuperCab 145""","3.7L V6 4X4, 6 passenger, cruise control, fog ...",Pre-Owned,"$16,800",wilfselieford,Used,2012,Ford,"F-150 STX 4WD SuperCab 145"""
4,2011 Ford Explorer Limited,"3.5L 4WD, black leather 6 passnger, adaptive c...",Pre-Owned,"$17,999",wilfselieford,Used,2011,Ford,Explorer Limited
5,2014 Ford Explorer Limited One Owner!,"** Low Mileage - One Owner ** 1.5L ecoboost, 5...",Pre-Owned,"$23,295",wilfselieford,Used,2014,Ford,Explorer Limited One Owner!
6,2020 Ford Escape SEL AWD,"7 passenger, black leather interior, navigatio...",Pre-Owned,"$28,600",wilfselieford,Used,2020,Ford,Escape SEL AWD
7,2015 GMC Yukon XL Denali - New Tires - DVD,"10941 kms! 2.3L ecoboot, 7 passenger black lea...",Pre-Owned,"$42,900",wilfselieford,Used,2015,GMC,Yukon XL Denali - New Tires - DVD
8,2020 Ford Explorer XLT 4WD,None,Pre-Owned,"$44,300",wilfselieford,Used,2020,Ford,Explorer XLT 4WD

In [15]:
df.drop(columns =["Title"], inplace = True)
df

,Description,Certification,Price,Dealer,Condition,Make Year,Make,Model
0,"black leather, power driver's seat, heated fro...",Pre-Owned,"$9,700",wilfselieford,Used,2009,Volkswagen,Tiguan Highline
1,"2.5L, front wheel drive, bluetooth, back up ca...",Pre-Owned,"$12,999",wilfselieford,Used,2017,Ford,Fusion SE
2,"5 passenger black leather, remote start, heate...",Pre-Owned,"$14,295",wilfselieford,Used,2014,Hyundai,Tucson GLS FWD 4dr Auto
3,"3.7L V6 4X4, 6 passenger, cruise control, fog ...",Pre-Owned,"$16,800",wilfselieford,Used,2012,Ford,"F-150 STX 4WD SuperCab 145"""
4,"3.5L 4WD, black leather 6 passnger, adaptive c...",Pre-Owned,"$17,999",wilfselieford,Used,2011,Ford,Explorer Limited
5,"** Low Mileage - One Owner ** 1.5L ecoboost, 5...",Pre-Owned,"$23,295",wilfselieford,Used,2014,Ford,Explorer Limited One Owner!
6,"7 passenger, black leather interior, navigatio...",Pre-Owned,"$28,600",wilfselieford,Used,2020,Ford,Escape SEL AWD
7,"10941 kms! 2.3L ecoboot, 7 passenger black lea...",Pre-Owned,"$42,900",wilfselieford,Used,2015,GMC,Yukon XL Denali - New Tires - DVD
8,None,Pre-Owned,"$44,300",wilfselieford,Used,2020,Ford,Explorer XLT 4WD

In [ ]:
#Dataframe to csv
df.to_csv('welfselieford.csv')