In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from selenium import webdriver
import time
from matplotlib import pyplot as plt

In [2]:
urla = "https://www.thecarstore.ca/vehicles/used/?st=make,asc&view=grid&sc=used"

In [3]:
driver=webdriver.Firefox(executable_path="C:/Users/DELL/Downloads/geckodriver.exe")
#set the value of executable path
driver.get(urla)

In [4]:
page_source=driver.page_source

In [5]:
#parsing the page
soup=BeautifulSoup(page_source,'html.parser')

In [6]:
#All the data present in a page is present in class: row grid-row
data = soup.findAll('div',{"class":"row grid-row"})
#printing the extracted data of a single page
for info in data:
    print(info.text)

      2012 Acura TSX Premium Pkg Sunroof Htd Leather Rear Cam !           Est. Finance Payment  $130
									/bw
								  Click to open payment calculator
								5% for 60 Months							  Dealer Price  $14,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: JH4CU2E55CC800490Kilometres: 115,200Condition: UsedBody Style: SedanEngine: 4 Cylinder Engine        Compare
				View More Details
			  Compare        2015 Acura MDX BLOW OUT PRICE!! sunroof NO ACCIDENTS! CLEAN TITLE           Est. Finance Payment  $200
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $26,929  Pricing excludes licensing and tax.
								+ Tax							     VIN: 5FRYD4H20FB503234Kilometres: 74,550Condition: UsedBody Style: SUVEngine: V-6 cyl        Compare
				View More Details
			  Compare        2016 Acura TLX V6 Tech LAUNCH Kit! Navi Leather Sunroof 1owner!           Est. Finance Payment  $186
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $24,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: 19UUB3F54GA801763Kilometres: 54,785Condition: UsedBody Style: SedanEngine: V6 Cylinder Engine        Compare
				View More Details
			  Compare        2016 Acura TLX SH-AWD V6 Tech sUNROOF hTD Leather rear cam           Est. Finance Payment  $178
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $23,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: 19UUB3F52GA801762Kilometres: 53,510Condition: UsedBody Style: SedanEngine: V6 Cylinder Engine        Compare
				View More Details
			  Compare        2014 Audi A5 Technik Navi REMOTE START park sensor BANG OLUFSEN           Est. Finance Payment  $171
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $22,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: WAUVFBFR5EA049344Kilometres: 68,810Condition: UsedBody Style: CoupeEngine: 4 cylinder        Compare
				View More Details
			  Compare        2013 Audi A4 Premium Plus, NAVI push start SUNROOF bluetooth           Est. Finance Payment  $191
									/bw
								  Click to open payment calculator
								5% for 60 Months							  Dealer Price  $21,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: WAUFFCFL9DN047433Kilometres: 54,125Condition: UsedBody Style: SedanEngine: 4 cylinder        Compare
				View More Details
			  Compare        2016 BMW 2 Series 228i xDrive M Sport PKG Navi Sunroof 1owner            Est. Finance Payment  $193
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $25,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: WBA1G9C58GV726307Kilometres: 57,900Condition: UsedBody Style: CoupeEngine: 4 Cylinder Engine        Compare
				View More Details
			  Compare        2017 BMW 3 Series 330Xi Harmon/Kardon Navi Prem Enhanced BMW WARANTY           Est. Finance Payment  $223
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $29,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: WBA8D9C38HA012367Kilometres: 42,556Condition: UsedBody Style: SedanEngine: 4 Cylinder Engine        Compare
				View More Details
			  Compare        2016 BMW 3 Series 328i xDrive Navi Park Sensor HEADS UP HARMON/KAR           Est. Finance Payment  $193
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $25,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: WBA8E3G55GNT75903Kilometres: 52,105Condition: UsedBody Style: SedanEngine: 4 Cylinder Engine        Compare
				View More Details
			  Compare        2012 BMW 1 Series 128i "M" Pkg-Sunroof Leather Rear Sensor Clean           Est. Finance Payment  $139
									/bw
								  Click to open payment calculator
								5% for 60 Months							  Dealer Price  $15,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: WBAUP7C53CVP24105Kilometres: 71,140Condition: UsedBody Style: CoupeEngine: Straight 6 Cylinder Engine        Compare
				View More Details
			  Compare        2015 Dodge Grand Caravan STOW-N-GO Bluetooth No Accidents! 1owner 7 seater            Est. Finance Payment  $126
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $16,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: 2c4rdgbg4fr725503Kilometres: 68,450Condition: UsedBody Style: MinivanEngine: 3.5        Compare
				View More Details
			  Compare        2016 Honda Odyssey EX NO ACCIDENTS! clean Carfax Rear CAm Htd Seat           Est. Finance Payment  $200
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $26,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: 5FNRL5H40GB513294Kilometres: 59,250Condition: UsedBody Style: MinivanEngine: V6 Cylinder Engine        Compare
				View More Details
			  Compare        2016 Honda Odyssey EX 1owner NO ACCIDENTS! Htd Seat Rear Cam BLuetoot           Est. Finance Payment  $193
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $25,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: 5FNRL5H42GB511837Kilometres: 73,485Condition: UsedBody Style: MinivanEngine: V6 Cylinder Engine        Compare
				View More Details
			  Compare        2016 Honda CR-V EX SUNROOF Rear Cam HTD SEAT Bluetooth Push strt           Est. Finance Payment  $171
									/bw
								  Click to open payment calculator
								5% for 72 Months							  Dealer Price  $22,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: 2HKRM4H58GH115526Kilometres: 72,480Condition: UsedBody Style: SUVEngine: 4 Cylinder Engine        Compare
				View More Details
			  Compare        2013 Hyundai Genesis Coupe 6spd Manual! Bluetooth Htd Seat B.C. CAR! NO SNOW!           Est. Finance Payment  $113
									/bw
								  Click to open payment calculator
								5% for 60 Months							  Dealer Price  $12,991  Pricing excludes licensing and tax.
								+ Tax							     VIN: KMHHT6KD2DU087827Kilometres: 98,480Condition: UsedBody Style: CoupeEngine: 4 Cylinder Engine        Compare
				View More Details
			  Compare

In [7]:
#Finding the titles of cars using find_all
#All the titles are present in div class : vehicle-card__details
car_titles = []
a=soup.findAll('div',{"class":"vehicle-card__details"})
for i in a :
    titles=i.find('h4',{"class":"vehicle-card__title"}).text.strip()#all the titles are inside h4 class
    print(titles)#printing titles
    car_titles.append(titles)#appending values
print(car_titles)#printing titles
len(car_titles)#printing length of list

2012 Acura TSX Premium Pkg Sunroof Htd Leather Rear Cam !
2015 Acura MDX BLOW OUT PRICE!! sunroof NO ACCIDENTS! CLEAN TITLE
2016 Acura TLX V6 Tech LAUNCH Kit! Navi Leather Sunroof 1owner!
2016 Acura TLX SH-AWD V6 Tech sUNROOF hTD Leather rear cam
2014 Audi A5 Technik Navi REMOTE START park sensor BANG OLUFSEN
2013 Audi A4 Premium Plus, NAVI push start SUNROOF bluetooth
2016 BMW 2 Series 228i xDrive M Sport PKG Navi Sunroof 1owner
2017 BMW 3 Series 330Xi Harmon/Kardon Navi Prem Enhanced BMW WARANTY
2016 BMW 3 Series 328i xDrive Navi Park Sensor HEADS UP HARMON/KAR
2012 BMW 1 Series 128i "M" Pkg-Sunroof Leather Rear Sensor Clean
2015 Dodge Grand Caravan STOW-N-GO Bluetooth No Accidents! 1owner 7 seater
2016 Honda Odyssey EX NO ACCIDENTS! clean Carfax Rear CAm Htd Seat
2016 Honda Odyssey EX 1owner NO ACCIDENTS! Htd Seat Rear Cam BLuetoot
2016 Honda CR-V EX SUNROOF Rear Cam HTD SEAT Bluetooth Push strt
2013 Hyundai Genesis Coupe 6spd Manual! Bluetooth Htd Seat B.C. CAR! NO SNOW!
['2012 Acura TSX Premium Pkg Sunroof Htd Leather Rear Cam !', '2015 Acura MDX BLOW OUT PRICE!! sunroof NO ACCIDENTS! CLEAN TITLE', '2016 Acura TLX V6 Tech LAUNCH Kit! Navi Leather Sunroof 1owner!', '2016 Acura TLX SH-AWD V6 Tech sUNROOF hTD Leather rear cam', '2014 Audi A5 Technik Navi REMOTE START park sensor BANG OLUFSEN', '2013 Audi A4 Premium Plus, NAVI push start SUNROOF bluetooth', '2016 BMW 2 Series 228i xDrive M Sport PKG Navi Sunroof 1owner', '2017 BMW 3 Series 330Xi Harmon/Kardon Navi Prem Enhanced BMW WARANTY', '2016 BMW 3 Series 328i xDrive Navi Park Sensor HEADS UP HARMON/KAR', '2012 BMW 1 Series 128i "M" Pkg-Sunroof Leather Rear Sensor Clean', '2015 Dodge Grand Caravan STOW-N-GO Bluetooth No Accidents! 1owner 7 seater', '2016 Honda Odyssey EX NO ACCIDENTS! clean Carfax Rear CAm Htd Seat', '2016 Honda Odyssey EX 1owner NO ACCIDENTS! Htd Seat Rear Cam BLuetoot', '2016 Honda CR-V EX SUNROOF Rear Cam HTD SEAT Bluetooth Push strt', '2013 Hyundai Genesis Coupe 6spd Manual! Bluetooth Htd Seat B.C. CAR! NO SNOW!']

15

In [8]:
#Finding the prices of cars using find_all
#All the prices are present in div class : vehicle-card__price-wrap
car_price = []
c = soup.findAll('div',{"class":"vehicle-card__price-wrap"})
for i in c :
    sp=i.findAll('div',{"class":"price-block__price price-block__price--lg price-block__price--primary"})#digging further
    for j in sp:
        s=j.find('span',{"class":"df aifs"}).text.split("df aifs")[0]#actual values are inside span class :df aifs
        print(s)#printing prices
        car_price.append(s)#appending in a list
print(car_price)#printing list
len(car_price)#length oflist

$14,991
$26,929
$24,991
$23,991
$22,991
$21,991
$25,991
$29,991
$25,991
$15,991
$16,991
$26,991
$25,991
$22,991
$12,991
['$14,991', '$26,929', '$24,991', '$23,991', '$22,991', '$21,991', '$25,991', '$29,991', '$25,991', '$15,991', '$16,991', '$26,991', '$25,991', '$22,991', '$12,991']

15

In [9]:
#Finding the discounted price on cars using find_all
#All the  discounted price  are present in div class : vehicle-card__price-wrap vehicle-card__price-wrap--finance
price = []
c = soup.findAll('div',{"class":"vehicle-card__price-wrap vehicle-card__price-wrap--finance"})
for i in c :
    sp=i.findAll('div',{"class":"price-block__single price-block__single--finance"})#digging further
    for j in sp:
        s=j.find('span',{"class":"df aifs"}).text.split("df aifs")[0]#actual values are inside span class :df aifs
        print(s)#printing initial prices
        price.append(s)#appending in a list
print(price)#printing list
len(price)#length oflist

$130
$200
$186
$178
$171
$191
$193
$223
$193
$139
$126
$200
$193
$171
$113
['$130', '$200', '$186', '$178', '$171', '$191', '$193', '$223', '$193', '$139', '$126', '$200', '$193', '$171', '$113']

15

In [10]:
#Finding the duration using find_all
#All the duration are present in div class : vehicle-card__price-wrap
duration = []
c = soup.findAll('div',{"class":"vehicle-card__price-wrap"})
for i in c :
    sp=i.findAll('div',{"class":"price-block__single price-block__single--finance"})#digging further
    for j in sp:
        s=j.find('span',{"class":"price-block__sub"}).text.replace("\t","")#actual values are inside span class :df aifs
        print(s)#printing prices
        duration.append(s.strip())#appending in a list
print(duration)#printing list
len(duration)#length oflist

5% for 60 Months

5% for 72 Months

5% for 72 Months

5% for 72 Months

5% for 72 Months

5% for 60 Months

5% for 72 Months

5% for 72 Months

5% for 72 Months

5% for 60 Months

5% for 72 Months

5% for 72 Months

5% for 72 Months

5% for 72 Months

5% for 60 Months
['5% for 60 Months', '5% for 72 Months', '5% for 72 Months', '5% for 72 Months', '5% for 72 Months', '5% for 60 Months', '5% for 72 Months', '5% for 72 Months', '5% for 72 Months', '5% for 60 Months', '5% for 72 Months', '5% for 72 Months', '5% for 72 Months', '5% for 72 Months', '5% for 60 Months']

15

In [11]:
Vinlist = []
Kmlist = []
condition = []
body_style = []
engine = []
# taking empty lists

#All the specifications are inside ul class: detailed-specs inline-view
spec= soup.find_all("ul",{"class": "detailed-specs"})

for i in spec:
    newsoup = BeautifulSoup(str(i),'html.parser')#using parser for scrapping inside details
    lis = newsoup.find_all('li')#finding all li inside ul
    for li in lis:
        if 'VIN' in li.text: # if present 
            Vinlist.append(li.text.replace("VIN:","")) # then append
        if 'Kilometres' in li.text:# if present
            Kmlist.append(li.text.replace("Kilometres:",""))# then append
        if 'Condition' in li.text:# if present
            condition.append(li.text.replace("Condition:",""))# then append# then append
        if 'Body Style' in li.text:# if present
            body_style.append(li.text.replace("Body Style:",""))# then append
        if 'Engine' in li.text:# if present
            engine.append(li.text.replace("Engine:",""))
            
#priniting individual lists
print(Vinlist)
print(Kmlist)
print(condition)
print(body_style)
print(engine)

[' JH4CU2E55CC800490', ' 5FRYD4H20FB503234', ' 19UUB3F54GA801763', ' 19UUB3F52GA801762', ' WAUVFBFR5EA049344', ' WAUFFCFL9DN047433', ' WBA1G9C58GV726307', ' WBA8D9C38HA012367', ' WBA8E3G55GNT75903', ' WBAUP7C53CVP24105', ' 2c4rdgbg4fr725503', ' 5FNRL5H40GB513294', ' 5FNRL5H42GB511837', ' 2HKRM4H58GH115526', ' KMHHT6KD2DU087827']
[' 115,200', ' 74,550', ' 54,785', ' 53,510', ' 68,810', ' 54,125', ' 57,900', ' 42,556', ' 52,105', ' 71,140', ' 68,450', ' 59,250', ' 73,485', ' 72,480', ' 98,480']
[' Used', ' Used', ' Used', ' Used', ' Used', ' Used', ' Used', ' Used', ' Used', ' Used', ' Used', ' Used', ' Used', ' Used', ' Used']
[' Sedan', ' SUV', ' Sedan', ' Sedan', ' Coupe', ' Sedan', ' Coupe', ' Sedan', ' Sedan', ' Coupe', ' Minivan', ' Minivan', ' Minivan', ' SUV', ' Coupe']
[' 4 Cylinder Engine', ' V-6 cyl', ' V6 Cylinder Engine', ' V6 Cylinder Engine', ' 4 cylinder', ' 4 cylinder', ' 4 Cylinder Engine', ' 4 Cylinder Engine', ' 4 Cylinder Engine', ' Straight 6 Cylinder Engine', ' 3.5', ' V6 Cylinder Engine', ' V6 Cylinder Engine', ' 4 Cylinder Engine', ' 4 Cylinder Engine']

In [12]:
#creating dict of scrapped data
dict = {
    'Title' : car_titles ,
    'Mileage' : Kmlist , 
    'VIN' : Vinlist ,
    'Condition' : condition ,
    'Body Style':body_style,
    'Engine' : engine ,
    'Price' : car_price,
    'Finance Payment /bw': price,
    'Finance Payment Duration':duration
}

In [13]:
#creating dataframe from dict
df = pd.DataFrame.from_dict(dict,orient = 'index').T
df

,Title,Mileage,VIN,Condition,Body Style,Engine,Price,Finance Payment /bw,Finance Payment Duration
0,2012 Acura TSX Premium Pkg Sunroof Htd Leather...,"115,200",JH4CU2E55CC800490,Used,Sedan,4 Cylinder Engine,"$14,991",$130,5% for 60 Months
1,2015 Acura MDX BLOW OUT PRICE!! sunroof NO ACC...,"74,550",5FRYD4H20FB503234,Used,SUV,V-6 cyl,"$26,929",$200,5% for 72 Months
2,2016 Acura TLX V6 Tech LAUNCH Kit! Navi Leathe...,"54,785",19UUB3F54GA801763,Used,Sedan,V6 Cylinder Engine,"$24,991",$186,5% for 72 Months
3,2016 Acura TLX SH-AWD V6 Tech sUNROOF hTD Leat...,"53,510",19UUB3F52GA801762,Used,Sedan,V6 Cylinder Engine,"$23,991",$178,5% for 72 Months
4,2014 Audi A5 Technik Navi REMOTE START park se...,"68,810",WAUVFBFR5EA049344,Used,Coupe,4 cylinder,"$22,991",$171,5% for 72 Months
5,"2013 Audi A4 Premium Plus, NAVI push start SUN...","54,125",WAUFFCFL9DN047433,Used,Sedan,4 cylinder,"$21,991",$191,5% for 60 Months
6,2016 BMW 2 Series 228i xDrive M Sport PKG Navi...,"57,900",WBA1G9C58GV726307,Used,Coupe,4 Cylinder Engine,"$25,991",$193,5% for 72 Months
7,2017 BMW 3 Series 330Xi Harmon/Kardon Navi Pre...,"42,556",WBA8D9C38HA012367,Used,Sedan,4 Cylinder Engine,"$29,991",$223,5% for 72 Months
8,2016 BMW 3 Series 328i xDrive Navi Park Sensor...,"52,105",WBA8E3G55GNT75903,Used,Sedan,4 Cylinder Engine,"$25,991",$193,5% for 72 Months
9,"2012 BMW 1 Series 128i ""M"" Pkg-Sunroof Leather...","71,140",WBAUP7C53CVP24105,Used,Coupe,Straight 6 Cylinder Engine,"$15,991",$139,5% for 60 Months
10,2015 Dodge Grand Caravan STOW-N-GO Bluetooth N...,"68,450",2c4rdgbg4fr725503,Used,Minivan,3.5,"$16,991",$126,5% for 72 Months
11,2016 Honda Odyssey EX NO ACCIDENTS! clean Carf...,"59,250",5FNRL5H40GB513294,Used,Minivan,V6 Cylinder Engine,"$26,991",$200,5% for 72 Months
12,2016 Honda Odyssey EX 1owner NO ACCIDENTS! Htd...,"73,485",5FNRL5H42GB511837,Used,Minivan,V6 Cylinder Engine,"$25,991",$193,5% for 72 Months
13,2016 Honda CR-V EX SUNROOF Rear Cam HTD SEAT B...,"72,480",2HKRM4H58GH115526,Used,SUV,4 Cylinder Engine,"$22,991",$171,5% for 72 Months
14,2013 Hyundai Genesis Coupe 6spd Manual! Blueto...,"98,480",KMHHT6KD2DU087827,Used,Coupe,4 Cylinder Engine,"$12,991",$113,5% for 60 Months

In [14]:
df['Condition'] = 'Used'
df['Dealer'] = 'thecarstore'

In [15]:
split_title = df["Title"].str.split(" ", n =4 , expand = True) 
# splitting Tile column

In [16]:
df["Make Year"]= split_title[0]

In [17]:
df["Make"]= split_title[1]

In [18]:
df["Model"]= split_title[2]

In [19]:
df.drop(columns =["Title"], inplace = True)

In [20]:
df

,Mileage,VIN,Condition,Body Style,Engine,Price,Finance Payment /bw,Finance Payment Duration,Dealer,Make Year,Make,Model
0,"115,200",JH4CU2E55CC800490,Used,Sedan,4 Cylinder Engine,"$14,991",$130,5% for 60 Months,thecarstore,2012,Acura,TSX
1,"74,550",5FRYD4H20FB503234,Used,SUV,V-6 cyl,"$26,929",$200,5% for 72 Months,thecarstore,2015,Acura,MDX
2,"54,785",19UUB3F54GA801763,Used,Sedan,V6 Cylinder Engine,"$24,991",$186,5% for 72 Months,thecarstore,2016,Acura,TLX
3,"53,510",19UUB3F52GA801762,Used,Sedan,V6 Cylinder Engine,"$23,991",$178,5% for 72 Months,thecarstore,2016,Acura,TLX
4,"68,810",WAUVFBFR5EA049344,Used,Coupe,4 cylinder,"$22,991",$171,5% for 72 Months,thecarstore,2014,Audi,A5
5,"54,125",WAUFFCFL9DN047433,Used,Sedan,4 cylinder,"$21,991",$191,5% for 60 Months,thecarstore,2013,Audi,A4
6,"57,900",WBA1G9C58GV726307,Used,Coupe,4 Cylinder Engine,"$25,991",$193,5% for 72 Months,thecarstore,2016,BMW,2
7,"42,556",WBA8D9C38HA012367,Used,Sedan,4 Cylinder Engine,"$29,991",$223,5% for 72 Months,thecarstore,2017,BMW,3
8,"52,105",WBA8E3G55GNT75903,Used,Sedan,4 Cylinder Engine,"$25,991",$193,5% for 72 Months,thecarstore,2016,BMW,3
9,"71,140",WBAUP7C53CVP24105,Used,Coupe,Straight 6 Cylinder Engine,"$15,991",$139,5% for 60 Months,thecarstore,2012,BMW,1
10,"68,450",2c4rdgbg4fr725503,Used,Minivan,3.5,"$16,991",$126,5% for 72 Months,thecarstore,2015,Dodge,Grand
11,"59,250",5FNRL5H40GB513294,Used,Minivan,V6 Cylinder Engine,"$26,991",$200,5% for 72 Months,thecarstore,2016,Honda,Odyssey
12,"73,485",5FNRL5H42GB511837,Used,Minivan,V6 Cylinder Engine,"$25,991",$193,5% for 72 Months,thecarstore,2016,Honda,Odyssey
13,"72,480",2HKRM4H58GH115526,Used,SUV,4 Cylinder Engine,"$22,991",$171,5% for 72 Months,thecarstore,2016,Honda,CR-V
14,"98,480",KMHHT6KD2DU087827,Used,Coupe,4 Cylinder Engine,"$12,991",$113,5% for 60 Months,thecarstore,2013,Hyundai,Genesis

In [ ]:
#Dataframe to csv
df.to_csv('thecarstore.csv')