In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from selenium import webdriver
import time
from matplotlib import pyplot as plt

In [2]:
urla = "https://www.westperimeter.com/vehicles/?fn=&pr=&mk=&md=&tr=&bs=&od=&yr=&v1=Passenger%20Vehicles"

In [3]:
driver=webdriver.Firefox(executable_path="C:/Users/DELL/Downloads/geckodriver.exe")
#set the value of executable path
driver.get(urla)

In [4]:
page_source=driver.page_source

In [5]:
#parsing the page
soup=BeautifulSoup(page_source,'html.parser')

In [6]:
#All the data present in a page is present in class row 
data=soup.findAll('div',{"class":"row"})
#printing the extracted data of a single page
for info in data:
    print(info.text)

 Search Inventory:
				  Search
 Search Inventory:
				  Search
    Save Vehicle  Set Price Alerts    Stock #: 5574 2016 Toyota Corolla Low KMS.* A/C *Power Grou...    View Pre-Owned Certification					  Pre-Owned Certification          Dealer Price  $16,900
									+ Tax								  Est. Finance Payment  $118
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5574VIN: 2T1BURHE8GC483898Exterior Colour: GreyKilometres: 41,462Body Style: Sedan
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5545 2018 Ford Escape SE*AWD*Htd. Seats*B/up Cam*B...    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $25,800
									+ Tax								  Est. Finance Payment  $179
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5545VIN: 1FMCU9GD4JUC72009Exterior Colour: BlackKilometres: 10,550Body Style: SUV
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5598 2016 Honda CR-V EX AWD **Htd Seats*Power Sunr...    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $27,500
									+ Tax								  Est. Finance Payment  $191
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5598VIN: 2HKRM4H55GH112910Exterior Colour: GreyKilometres: 51,173Body Style: SUV
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5374 2014 Ford Escape     View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $15,900
									+ Tax								  Est. Finance Payment  $125
										/bw
									  Click to open payment calculator
									6.99% for 72 Months								    Stock #: 5374VIN: 1FMCU9G97EUD11124Exterior Colour: GreyKilometres: 89,972Body Style: SUV
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5478 2015 Ford Focus SE BLUETOOTH, BACKUPCAM, ALLO...    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $13,785
									+ Tax								  Est. Finance Payment  $96
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5478VIN: 1FADP3K23FL331892Exterior Colour: SilverKilometres: 49,933Body Style: Hatchback
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5600 2017 Dodge Grand Caravan SXT**STO & GO **Blue...    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $19,900
									+ Tax								  Est. Finance Payment  $138
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5600VIN: 2C4RDGBG7HR647379Exterior Colour: SilverKilometres: 99,971Body Style: Minivan
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5577 2016 Chevrolet Equinox LTZ AWD **SUNROOF*HEAT...    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $24,500
									+ Tax								  Est. Finance Payment  $170
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5577VIN: 2GNFLGEK0G6298935Exterior Colour: GreyKilometres: 51,346Body Style: SUV
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5412 2017 Ford Fusion Titanium AWD, Navigation, Ht...    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $23,950
									+ Tax								  Est. Finance Payment  $167
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5412VIN: 3FA6P0D95HR330927Exterior Colour: GreyKilometres: 25,753Body Style: Sedan
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5404 2017 Ford Focus SE**Bluetooth* Heated Seats* ...    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $16,500
									+ Tax								  Est. Finance Payment  $115
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5404VIN: 1FADP3F25HL239941Exterior Colour: WhiteKilometres: 31,182Body Style: Sedan
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5450 2016 Toyota Corolla LE **Heated Seats**Back-u...    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $16,490
									+ Tax								  Est. Finance Payment  $115
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5450VIN: 2T1BURHE5GC659810Exterior Colour: GreyKilometres: 46,510Body Style: Sedan
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5329 2017 Ford Taurus LIMITED **ALL WHEEL DRIVE**    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $23,987
									+ Tax								  Est. Finance Payment  $167
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5329VIN: 1FAHP2J80HG120369Exterior Colour: SilverKilometres: 28,622Body Style: Sedan
				View More Details
			   Compare     Compare      Save Vehicle  Set Price Alerts    Stock #: 5141 2016 Mitsubishi Lancer ES **Automatic**Tint**...    View Pre-Owned Certification					  Pre-Owned Certification      Watch Video Watch Video    Dealer Price  $14,984
									+ Tax								  Est. Finance Payment  $104
										/bw
									  Click to open payment calculator
									6.99% for 84 Months								    Stock #: 5141VIN: JA32U2FU9GU600567Exterior Colour: RedKilometres: 23,667Body Style: Sedan
				View More Details
			   Compare     Compare
1Personalize Your Options 2Apply For Financing Let’s Structure a Deal That Works For You We understand that purchasing a vehicle is a big decision, so we want you to be paying a price that you’re comfortable with. Let’s structure a deal that works for you below:  Apply Now                                         Please leave this field empty. Full Name* Email* Phone Number Preferred Contact Method---CallEmailText Message I agree to receive periodical offers, newsletter, safety and recall updates from the dealership. Consent can be withdrawn at any time.



Contact Us






Sales


(855) 874-6524






Email Us







Hours Of Operation





Sales



Service and Collision






Mon - Tue
9:00AM - 7:00PM


Wed - Fri
9:00AM - 6:00PM


Sat
9:00AM - 5:00PM


Sun
Closed






Mon - Fri
8:00AM - 5:00PM


Sat - Sun
Closed











Visit Our Location

3811 Portage Ave, Winnipeg, MB, R3K0X7, Canada

Get Directions




Connect With Us


FacebookTwitter

In [7]:
#Finding the titles of cars using find_all
#All the titles are present in h4 class : vehicle-card__title 
car_titles = []
a=soup.findAll('h4',{"class":"vehicle-card__title"})
for i in a :
    print(i.text)#printing titles
    car_titles.append(i.text)#appending values
print(car_titles)#printing titles
len(car_titles)#printing length of list

2016 Toyota Corolla Low KMS.* A/C *Power Grou...
2018 Ford Escape SE*AWD*Htd. Seats*B/up Cam*B...
2016 Honda CR-V EX AWD **Htd Seats*Power Sunr...
2014 Ford Escape
2015 Ford Focus SE BLUETOOTH, BACKUPCAM, ALLO...
2017 Dodge Grand Caravan SXT**STO & GO **Blue...
2016 Chevrolet Equinox LTZ AWD **SUNROOF*HEAT...
2017 Ford Fusion Titanium AWD, Navigation, Ht...
2017 Ford Focus SE**Bluetooth* Heated Seats* ...
2016 Toyota Corolla LE **Heated Seats**Back-u...
2017 Ford Taurus LIMITED **ALL WHEEL DRIVE**
2016 Mitsubishi Lancer ES **Automatic**Tint**...
['2016 Toyota Corolla Low KMS.* A/C *Power Grou...', '2018 Ford Escape SE*AWD*Htd. Seats*B/up Cam*B...', '2016 Honda CR-V EX AWD **Htd Seats*Power Sunr...', '2014 Ford Escape ', '2015 Ford Focus SE BLUETOOTH, BACKUPCAM, ALLO...', '2017 Dodge Grand Caravan SXT**STO & GO **Blue...', '2016 Chevrolet Equinox LTZ AWD **SUNROOF*HEAT...', '2017 Ford Fusion Titanium AWD, Navigation, Ht...', '2017 Ford Focus SE**Bluetooth* Heated Seats* ...', '2016 Toyota Corolla LE **Heated Seats**Back-u...', '2017 Ford Taurus LIMITED **ALL WHEEL DRIVE**', '2016 Mitsubishi Lancer ES **Automatic**Tint**...']

12

In [8]:
Vinlist = []
mileage = []
exterior = []
body_style = []
stock = []
# taking empty lists

#All the specifications are inside ul class: detailed-specs 
spec= soup.find_all("ul",{"class": "detailed-specs"})

for i in spec:
    newsoup = BeautifulSoup(str(i),'html.parser')#using parser for scrapping inside details
    lis = newsoup.find_all('li')#finding all li inside ul
    for li in lis:
       
        if 'VIN' in li.text: # if present 
            Vinlist.append(li.text.replace("VIN:","")) # then append
        if 'Kilometres' in li.text:# if present
            mileage.append(li.text.replace("Kilometres: ",""))# then append
        if 'Body Style' in li.text:# if present
            body_style.append(li.text.replace("Body Style:",""))# then append
        if 'Exterior' in li.text:# if present
            exterior.append(li.text.replace("Exterior Colour:",""))# then append# then append
        if 'Stock' in li.text:# if present
            stock.append(li.text.replace("Stock #:",""))#then append
            
#priniting individual lists
print(Vinlist)
print(mileage)
print(body_style)
print(exterior)
print(stock)

[' 2T1BURHE8GC483898', ' 1FMCU9GD4JUC72009', ' 2HKRM4H55GH112910', ' 1FMCU9G97EUD11124', ' 1FADP3K23FL331892', ' 2C4RDGBG7HR647379', ' 2GNFLGEK0G6298935', ' 3FA6P0D95HR330927', ' 1FADP3F25HL239941', ' 2T1BURHE5GC659810', ' 1FAHP2J80HG120369', ' JA32U2FU9GU600567']
['41,462', '10,550', '51,173', '89,972', '49,933', '99,971', '51,346', '25,753', '31,182', '46,510', '28,622', '23,667']
[' Sedan', ' SUV', ' SUV', ' SUV', ' Hatchback', ' Minivan', ' SUV', ' Sedan', ' Sedan', ' Sedan', ' Sedan', ' Sedan']
[' Grey', ' Black', ' Grey', ' Grey', ' Silver', ' Silver', ' Grey', ' Grey', ' White', ' Grey', ' Silver', ' Red']
[' 5574', ' 5545', ' 5598', ' 5374', ' 5478', ' 5600', ' 5577', ' 5412', ' 5404', ' 5450', ' 5329', ' 5141']

In [9]:
#Finding the initial discount on cars using find_all
#All the  initial discount  are present in div class :vehicle-card__price-wrap
car_price = []
c = soup.findAll('div',{"class":"vehicle-card__price-wrap"})
for i in c :
    sp=i.findAll('div',{"class":"price-block__price price-block__price--sm price-block__price--primary"})#digging further
    for j in sp:
        s=j.find('span',{"class":"df aifs"}).text.split("df aifs")[0]#actual values are inside span class :df aifs
        print(s)#printing initial prices
        car_price.append(s)#appending in a list
print(car_price)#printing list
len(car_price)#length oflist

$118
$179
$191
$125
$96
$138
$170
$167
$115
$115
$167
$104
['$118', '$179', '$191', '$125', '$96', '$138', '$170', '$167', '$115', '$115', '$167', '$104']

12

In [10]:
#Finding the discounted price on cars using find_all
#All the  discounted price  are present in div class : price-block__single price-block--expanded price-block__single--finance
price = []
c = soup.findAll('div',{"class":"price-block__single price-block__single--finance"})
for i in c :
    sp=i.findAll('div',{"class":"price-block__price price-block__price--sm price-block__price--dark"})#digging further
    for j in sp:
        s=j.find('span',{"class":"df aifs"}).text.split("df aifs")[0]#actual values are inside span class :df aifs
        print(s)#printing discounted prices
        price.append(s)#appending in a list
print(price)#printing list
len(price)#length oflist

$16,900
$25,800
$27,500
$15,900
$13,785
$19,900
$24,500
$23,950
$16,500
$16,490
$23,987
$14,984
['$16,900', '$25,800', '$27,500', '$15,900', '$13,785', '$19,900', '$24,500', '$23,950', '$16,500', '$16,490', '$23,987', '$14,984']

12

In [11]:
#Finding the duration using find_all
#All the duration are present in div class : vehicle-card__price-wrap
duration = []
c = soup.findAll('div',{"class":"vehicle-card__price-wrap vehicle-card__price-wrap--finance"})
for i in c :
    s=i.find('span',{"class":"price-block__sub"})#actual values are inside span class :df aifs
    print(s.text.strip())#printing prices
    duration.append(s.text.strip())#appending in a list
print(duration)#printing list
len(duration)#length oflist

6.99% for 84 Months
6.99% for 84 Months
6.99% for 84 Months
6.99% for 72 Months
6.99% for 84 Months
6.99% for 84 Months
6.99% for 84 Months
6.99% for 84 Months
6.99% for 84 Months
6.99% for 84 Months
6.99% for 84 Months
6.99% for 84 Months
['6.99% for 84 Months', '6.99% for 84 Months', '6.99% for 84 Months', '6.99% for 72 Months', '6.99% for 84 Months', '6.99% for 84 Months', '6.99% for 84 Months', '6.99% for 84 Months', '6.99% for 84 Months', '6.99% for 84 Months', '6.99% for 84 Months', '6.99% for 84 Months']

12

In [16]:
#creating dict of scrapped data
dict = {
    'Title' : car_titles ,
    'Mileage' : mileage, 
    'Body Style': body_style ,
    'VIN' : Vinlist ,
    'Stock' : stock ,
    'Exterior' : exterior ,
    'Price' : price,
    'Finance Payment/bw': car_price,
    'Finance Payment Duration':duration
}

In [17]:
df = pd.DataFrame.from_dict(dict,orient = 'index').T
df

,Title,Mileage,Body Style,VIN,Stock,Exterior,Price,Finance Payment/bw,Finance Payment Duration
0,2016 Toyota Corolla Low KMS.* A/C *Power Grou...,"41,462",Sedan,2T1BURHE8GC483898,5574,Grey,"$16,900",$118,6.99% for 84 Months
1,2018 Ford Escape SE*AWD*Htd. Seats*B/up Cam*B...,"10,550",SUV,1FMCU9GD4JUC72009,5545,Black,"$25,800",$179,6.99% for 84 Months
2,2016 Honda CR-V EX AWD **Htd Seats*Power Sunr...,"51,173",SUV,2HKRM4H55GH112910,5598,Grey,"$27,500",$191,6.99% for 84 Months
3,2014 Ford Escape,"89,972",SUV,1FMCU9G97EUD11124,5374,Grey,"$15,900",$125,6.99% for 72 Months
4,"2015 Ford Focus SE BLUETOOTH, BACKUPCAM, ALLO...","49,933",Hatchback,1FADP3K23FL331892,5478,Silver,"$13,785",$96,6.99% for 84 Months
5,2017 Dodge Grand Caravan SXT**STO & GO **Blue...,"99,971",Minivan,2C4RDGBG7HR647379,5600,Silver,"$19,900",$138,6.99% for 84 Months
6,2016 Chevrolet Equinox LTZ AWD **SUNROOF*HEAT...,"51,346",SUV,2GNFLGEK0G6298935,5577,Grey,"$24,500",$170,6.99% for 84 Months
7,"2017 Ford Fusion Titanium AWD, Navigation, Ht...","25,753",Sedan,3FA6P0D95HR330927,5412,Grey,"$23,950",$167,6.99% for 84 Months
8,2017 Ford Focus SE**Bluetooth* Heated Seats* ...,"31,182",Sedan,1FADP3F25HL239941,5404,White,"$16,500",$115,6.99% for 84 Months
9,2016 Toyota Corolla LE **Heated Seats**Back-u...,"46,510",Sedan,2T1BURHE5GC659810,5450,Grey,"$16,490",$115,6.99% for 84 Months
10,2017 Ford Taurus LIMITED **ALL WHEEL DRIVE**,"28,622",Sedan,1FAHP2J80HG120369,5329,Silver,"$23,987",$167,6.99% for 84 Months
11,2016 Mitsubishi Lancer ES **Automatic**Tint**...,"23,667",Sedan,JA32U2FU9GU600567,5141,Red,"$14,984",$104,6.99% for 84 Months

In [18]:
df['Dealer'] = 'westperimeter'
df['Condition'] = 'Used'

In [19]:
split_title = df["Title"].str.split(" ", n = 3, expand = True) 
# splitting Tile column 
df["Make Year"]= split_title[0] 
df["Make"]= split_title[1] 
df["Model"]= split_title[2] 
df

,Title,Mileage,Body Style,VIN,Stock,Exterior,Price,Finance Payment/bw,Finance Payment Duration,Dealer,Condition,Make Year,Make,Model
0,2016 Toyota Corolla Low KMS.* A/C *Power Grou...,"41,462",Sedan,2T1BURHE8GC483898,5574,Grey,"$16,900",$118,6.99% for 84 Months,westperimeter,Used,2016,Toyota,Corolla
1,2018 Ford Escape SE*AWD*Htd. Seats*B/up Cam*B...,"10,550",SUV,1FMCU9GD4JUC72009,5545,Black,"$25,800",$179,6.99% for 84 Months,westperimeter,Used,2018,Ford,Escape
2,2016 Honda CR-V EX AWD **Htd Seats*Power Sunr...,"51,173",SUV,2HKRM4H55GH112910,5598,Grey,"$27,500",$191,6.99% for 84 Months,westperimeter,Used,2016,Honda,CR-V
3,2014 Ford Escape,"89,972",SUV,1FMCU9G97EUD11124,5374,Grey,"$15,900",$125,6.99% for 72 Months,westperimeter,Used,2014,Ford,Escape
4,"2015 Ford Focus SE BLUETOOTH, BACKUPCAM, ALLO...","49,933",Hatchback,1FADP3K23FL331892,5478,Silver,"$13,785",$96,6.99% for 84 Months,westperimeter,Used,2015,Ford,Focus
5,2017 Dodge Grand Caravan SXT**STO & GO **Blue...,"99,971",Minivan,2C4RDGBG7HR647379,5600,Silver,"$19,900",$138,6.99% for 84 Months,westperimeter,Used,2017,Dodge,Grand
6,2016 Chevrolet Equinox LTZ AWD **SUNROOF*HEAT...,"51,346",SUV,2GNFLGEK0G6298935,5577,Grey,"$24,500",$170,6.99% for 84 Months,westperimeter,Used,2016,Chevrolet,Equinox
7,"2017 Ford Fusion Titanium AWD, Navigation, Ht...","25,753",Sedan,3FA6P0D95HR330927,5412,Grey,"$23,950",$167,6.99% for 84 Months,westperimeter,Used,2017,Ford,Fusion
8,2017 Ford Focus SE**Bluetooth* Heated Seats* ...,"31,182",Sedan,1FADP3F25HL239941,5404,White,"$16,500",$115,6.99% for 84 Months,westperimeter,Used,2017,Ford,Focus
9,2016 Toyota Corolla LE **Heated Seats**Back-u...,"46,510",Sedan,2T1BURHE5GC659810,5450,Grey,"$16,490",$115,6.99% for 84 Months,westperimeter,Used,2016,Toyota,Corolla
10,2017 Ford Taurus LIMITED **ALL WHEEL DRIVE**,"28,622",Sedan,1FAHP2J80HG120369,5329,Silver,"$23,987",$167,6.99% for 84 Months,westperimeter,Used,2017,Ford,Taurus
11,2016 Mitsubishi Lancer ES **Automatic**Tint**...,"23,667",Sedan,JA32U2FU9GU600567,5141,Red,"$14,984",$104,6.99% for 84 Months,westperimeter,Used,2016,Mitsubishi,Lancer

In [20]:
df.drop(columns =["Title"], inplace = True)
df

,Mileage,Body Style,VIN,Stock,Exterior,Price,Finance Payment/bw,Finance Payment Duration,Dealer,Condition,Make Year,Make,Model
0,"41,462",Sedan,2T1BURHE8GC483898,5574,Grey,"$16,900",$118,6.99% for 84 Months,westperimeter,Used,2016,Toyota,Corolla
1,"10,550",SUV,1FMCU9GD4JUC72009,5545,Black,"$25,800",$179,6.99% for 84 Months,westperimeter,Used,2018,Ford,Escape
2,"51,173",SUV,2HKRM4H55GH112910,5598,Grey,"$27,500",$191,6.99% for 84 Months,westperimeter,Used,2016,Honda,CR-V
3,"89,972",SUV,1FMCU9G97EUD11124,5374,Grey,"$15,900",$125,6.99% for 72 Months,westperimeter,Used,2014,Ford,Escape
4,"49,933",Hatchback,1FADP3K23FL331892,5478,Silver,"$13,785",$96,6.99% for 84 Months,westperimeter,Used,2015,Ford,Focus
5,"99,971",Minivan,2C4RDGBG7HR647379,5600,Silver,"$19,900",$138,6.99% for 84 Months,westperimeter,Used,2017,Dodge,Grand
6,"51,346",SUV,2GNFLGEK0G6298935,5577,Grey,"$24,500",$170,6.99% for 84 Months,westperimeter,Used,2016,Chevrolet,Equinox
7,"25,753",Sedan,3FA6P0D95HR330927,5412,Grey,"$23,950",$167,6.99% for 84 Months,westperimeter,Used,2017,Ford,Fusion
8,"31,182",Sedan,1FADP3F25HL239941,5404,White,"$16,500",$115,6.99% for 84 Months,westperimeter,Used,2017,Ford,Focus
9,"46,510",Sedan,2T1BURHE5GC659810,5450,Grey,"$16,490",$115,6.99% for 84 Months,westperimeter,Used,2016,Toyota,Corolla
10,"28,622",Sedan,1FAHP2J80HG120369,5329,Silver,"$23,987",$167,6.99% for 84 Months,westperimeter,Used,2017,Ford,Taurus
11,"23,667",Sedan,JA32U2FU9GU600567,5141,Red,"$14,984",$104,6.99% for 84 Months,westperimeter,Used,2016,Mitsubishi,Lancer

In [ ]:
#Dataframe to csv
df.to_csv('westperimeter.csv')